version: "3"

services:
  webapp:
    image: romitsutariya/springapp:1.0
    ports:
      - "80:8080"
    networks:
      - back-tier
    depends_on:
      - mysqldb   
  mysqldb:
    image: romitsutariya/mysql_spring:1.0
    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier:
